### ISSUE TITLE
Disable compatibility mode

### ISSUE THREAD

**Issue by SheepTester** [SheepTester/scratch-gui#13]
From Discord:

> wondering if i can disable the compatability mode thing in E羊icques so i can run it at 60fps before converting to html

Can be a URL parameter: `?compatibility=false`

**Comment by e-l-i-j-a-h** [comment]
wow

**Comment by SheepTester** [comment]
Added in ff4bea2a5d5649333a670dd9cd5a876e609b9e4c but I forgot to document it in the README oops
