### ISSUE TITLE
Note that websocket must be wss or localhost

### ISSUE THREAD

**Issue by SheepTester** [SheepTester/scratch-gui#34]
in flags.html

htmlifier too?

from [here](https://discord.com/channels/775792479844696084/775792479844696087/793268057128697877)

**Comment by itzjakm** [comment]
"htmlifier too?"
It depends, if the HTMLified file is put on a server activating HTTPS (I'm not sure how activating it works) it probably won't work, if the file is used locally or with HTTP it works
