### ISSUE TITLE
Which exactly is an Extension URL ? Can it run ScratchX extensions?

### ISSUE THREAD

**Issue by SparkScratch-P** [SheepTester/scratch-gui#41]
### **I had been searching for this exciting feature in sb3, and got it!**

For the '_Choose an Extension_' option, which exactly is the URL to be placed? 

![image](https://user-images.githubusercontent.com/73777108/111056064-119cf700-84a2-11eb-9fae-e2d108e6f6dd.png)

In the above image, is it the Red one or the blue one..... or anything else?
Can we use ScratchX extensions here. The above pic is from there https://github.com/khanning/scratch-arduino-extension

### Pls Help me

**Comment by SheepTester** [comment]
Scratch extensions made for Scratch 2.0 aren't compatible with Scratch 3.0. The ST only guarantees backwards compatibility for Scratch projects.

**Comment by SparkScratch-P** [comment]
I understand, **but pls tell me...,**
 ### Which one is the URL?
[https://github.com/MrYsLab/s3onegpio](https://github.com/MrYsLab/s3onegpio) is said to be made for scratch 3. 
### The red one, or blue one, in the following image, or anything else?
![image](https://user-images.githubusercontent.com/73777108/111059451-a3652e00-84bb-11eb-9da1-b5a3d5e90a18.png)

**Comment by SheepTester** [comment]
My mod only supports [unofficial extensions](https://github.com/LLK/scratch-vm/blob/develop/docs/extensions.md#types-of-extensions); extensions that require modding the editor are not supported

**Comment by SparkScratch-P** [comment]
ok
