### ISSUE TITLE
What are the extensions?

### ISSUE THREAD

**Issue by Emerald-chaos** [SheepTester/scratch-gui#47]

**Comment by SheepTester** [comment]
I need more context. "Extensions" could refer to different things depending on the context, even for this mod

**Comment by Emerald-chaos** [comment]
> I need more context. "Extensions" could refer to different things depending on the context, even for this mod

Okay, so... I know NitroBlock, and Utilities.

**Comment by SheepTester** [comment]
Oh, unofficial Scratch 3.0 extensions are a type of Scratch 3.0 extensions that can add custom blocks defined in JavaScript to widen the walls of Scratch. According to [the Scratch Team's documentation](https://github.com/LLK/scratch-vm/blob/develop/docs/extensions.md#types-of-extensions), unofficial extensions are neither developed nor maintained by the ST, and they aren't listed in the extensions library. In my mod, you have to add them by specifying a link to the JavaScript file defining your unofficial extension. They're also sandboxed in a [web worker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers), which have access to [these global variables](https://developer.mozilla.org/en-US/docs/Web/API/DedicatedWorkerGlobalScope). Projects using unofficial extensions cannot be shared to the community.
