### ISSUE TITLE
My extension does not work! (again!)

### ISSUE THREAD

**Issue by Time-dragon** [SheepTester/scratch-gui#48]
### Expected Behavior
My extension at https://github.com/Emerald-chaos/bump-bump-bump-bump-bump/blob/main/extension.js should load.
### Actual Behavior
It does not.
### Steps to Reproduce
Try loading it.
### Operating System and Browser
Chrome OS and Chrome

**Comment by SheepTester** [comment]
You should use the inspect element console (on Chrome, option + command + J on Macs, ctrl + shift + J everywhere else) to see what the errors are.

![image](https://user-images.githubusercontent.com/22133785/117234789-8291c880-adda-11eb-952c-ac5e68289384.png)

> Refused to execute script from 'https://github.com/Emerald-chaos/bump-bump-bump-bump-bump/blob/main/extension.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

https://github.com/Emerald-chaos/bump-bump-bump-bump-bump/blob/main/extension.js is an HTML web page. If you right click > View page source, you can see that it is not valid JavaScript:

![image](https://user-images.githubusercontent.com/22133785/117234873-a7863b80-adda-11eb-955a-8a80c63b2311.png)


You should enable [GitHub Pages](https://pages.github.com/) on your repository and then use the JavaScript file hosted on GitHub Pages instead.

**Comment by Emerald-chaos** [comment]
> You should enable [GitHub Pages](https://pages.github.com/) on your repository and then use the JavaScript file hosted on GitHub Pages instead.

I tried and still a no.

**Comment by SheepTester** [comment]
What does the console say?

**Comment by Emerald-chaos** [comment]
> What does the console say?
![Screenshot 2021-05-06 at 2 28 19 PM](https://user-images.githubusercontent.com/82837930/117347700-62fcad80-ae77-11eb-8d46-2c9bb74ab11f.png)

**Comment by SheepTester** [comment]
Okay, I manually reviewed your code.

You can't have spaces in identifiers like class names in JavaScript:

```js
class Improved Utilities {
```

You need to use the same class name here:

```js
Scratch.extensions.register (new Utilities ());
```

Also, the spacing is quite weird. Did you run this through a spell checker made for English?

You can't have spaces in a data URL, but this won't stop the extension from working:

```js
const icon = "data: image / png; base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAADTUlEQVRIS63VTWgUZxgH8P 7Mzsf + + 2U2SrPJKBoEA1WKUMzupaKHpgoetadCnaBN9FRaLLRQEW17KKIed1V21dJLbU / FRqiixx219NDaVi NmnWNZT + + + cze7Ozsf7yoxEYpnMRJI5DQzP 5v3P8 / 7DEHANVHM7iXAVyAkwQCNgZYjDp3KH7jzZ1DdwmckBLirrE29KQgcTNOBZTrQdYP2es631LSPnp34zQqDlgTIcvTlOowxNBsG6o3uHw6he899eOt + EBIGeBHxUW5ElDjEYwKSKdFbzzAsVB61 / q4lWlsvv3 / XXAwJBOaL9pe29slE3MgoOSHF + N0DAwnwfASNehe1WudkYVw7sixgYfFkMXtSikU / VZQU3LhmHjVZ17Sz59Tbt / 2QJe3glUIGMnEhe3PgjcR2Ny5dN / Df0873ebX8gS / wshUBUMK PKveuhzWGZPF0fdiceHq4FAK3a6FyoyuFca13GKA14ruw8qM + / + ldhXNscBnz03duDUSY83jCchu04ePBvs5ZXtTW wGQpW12 / IZ1xP9r0dAM9g2bOH9Rmg5DDpW0ZwvFVD7CpW1ctqNqQP1DM / ZJRErvdFqw bqHdMccKqvZr4AEsbdsVj4lTbkTttolqtXWloGp7FtlB7uv + + + 1fIX6bSM9pyJJ9W5a3m1PAYC5ou4H7mUvT44mNwZTwio17to1Dsn8qp21Bc4cGl0WCLcP vW9wkRQrxddNrW6cyw9NmxnTfthUX7ftgs9LcTP8dkfmxIWeW16cOHTdO22EheLU8v2qYTxezn6bT8zeo1MS / T2dk5GB3rHgNOMD6 + SsFxnE3eJcAnohwdUZQkQAjqtTYadePHwri2L / CgHbuxg3 / ywPhdUZJbJOnF3GnpPS9fw7ABAkgij3h8flS46REYPRvVig5KoebV8oXAg3bw4ugmjkV + 6U + Xt / T1SSDE / wy6sTxrdiHHBYgCH4q8ssqLjOPHZYk / kkiKEUHg4Y5qBgbLpDBNG62W5Rhde4rjsGdISUEUgxHf1zx0MfsWdTBGCHIAeQeABbAyBdPmfziTpdz SASlMOT1Z9GCoJeCLAtwrTBk2UAYsiKAH + + JN2YreXDHg / wilzJ3Oz1YUmEcYY2fce0LIx88BFi6vvp70RPYAAAAASUVORK5CYII = ";
```

**Comment by SheepTester** [comment]
You can't have a space between `>` and `=`:

```js
    return A> = B;
```

**Comment by Time-dragon** [comment]
Fixed it but now blocks are stuck and I'm scared

**Comment by SheepTester** [comment]
Maybe have a look at the console again?

![image](https://user-images.githubusercontent.com/22133785/122594846-6fe6f200-d01c-11eb-88db-3bdfb526d471.png)

https://github.com/Time-dragon/bump-bump-bump-bump-bump/blob/main/extension.js#L12-L14

**Comment by Time-dragon** [comment]
> Maybe have a look at the console again?
> 
> ![image](https://user-images.githubusercontent.com/22133785/122594846-6fe6f200-d01c-11eb-88db-3bdfb526d471.png)
> 
> https://github.com/Time-dragon/bump-bump-bump-bump-bump/blob/main/extension.js#L12-L14

I fixed it. Screenshot the tab to see the new results.

**Comment by Time-dragon** [comment]
> Maybe have a look at the console again?
> 
> ![image](https://user-images.githubusercontent.com/22133785/122594846-6fe6f200-d01c-11eb-88db-3bdfb526d471.png)
> 
> https://github.com/Time-dragon/bump-bump-bump-bump-bump/blob/main/extension.js#L12-L14

I fixed it. Screenshot the tab to see if the blocks are still stuck together.

**Comment by Time-dragon** [comment]
@SheepTester see above comment

**Comment by SheepTester** [comment]
![image](https://user-images.githubusercontent.com/22133785/122624301-6f6a4d80-d054-11eb-9369-3632c1f711f8.png)
I'm assuming it works now?

**Comment by Time-dragon** [comment]
It works!
![Screenshot 2021-06-19 at 12 26 03 PM](https://user-images.githubusercontent.com/82837930/122648997-be1df300-d0f9-11eb-9cbc-06cddd72ffcb.png)

**Comment by Time-dragon** [comment]
@SheepTester So I renamed it and it broke AGAIN and also I removed the icon.

**Comment by SheepTester** [comment]
You create a class named `Improved_Utilities`

```js
class Improved_Utilities {
```

but then you create an instance of some class `ImprovedUtil`

```js
Scratch.extensions.register (new ImprovedUtil ());
```

**Comment by SheepTester** [comment]
You also make reference to `icon` in on line 14, which is not defined

https://github.com/Time-dragon/extension-bin/blob/2e9a2ecf701112b8392c7754cac14ed71bc920a0/util.js#L14

**Comment by Time-dragon** [comment]
Thanks! Resolving.

**Comment by SheepTester** [comment]
You should use [ESLint](https://eslint.org/demo#eyJ0ZXh0IjoiLyogZ2xvYmFsIGZldGNoLCBTY3JhdGNoICovXG5cbmNsYXNzIEltcHJvdmVkX1V0aWxpdGllcyB7XG5cbiAgY29uc3RydWN0b3IgKCkge31cblxuICBnZXRJbmZvICgpIHtcbiAgICByZXR1cm4ge1xuICAgICAgaWQ6ICd1dGlsaXRpZXMnLFxuICAgICAgbmFtZTogJ0ltcHJvdmVkIFV0aWxpdGllcycsXG5cbiAgICAgIGNvbG9yMTogJyM4QkMzNEEnLFxuICAgICAgY29sb3IyOiAnIzdDQjM0MicsXG4gICAgICBjb2xvcjM6ICcjNjg5RjM4JyxcblxuICAgICAgbWVudUljb25VUkk6IGljb24sXG5cbiAgICAgIGJsb2NrczogW1xuICAgICAgICB7XG4gICAgICAgICAgb3Bjb2RlOiAnaXNFeGFjdGx5JyxcblxuICAgICAgICAgIGJsb2NrVHlwZTogU2NyYXRjaC5CbG9ja1R5cGUuQk9PTEVBTixcblxuICAgICAgICAgIHRleHQ6ICdpcyBzdHJpbmcgW0FdIGV4YWN0bHkgW0JdPycsXG4gICAgICAgICAgYXJndW1lbnRzOiB7XG4gICAgICAgICAgICBBOiB7XG4gICAgICAgICAgICAgIHR5cGU6IFNjcmF0Y2guQXJndW1lbnRUeXBlLlNUUklORyxcbiAgICAgICAgICAgICAgZGVmYXVsdFZhbHVlOiAnaGVsbG8gd29ybGQnXG4gICAgICAgICAgICB9LFxuICAgICAgICAgICAgQjoge1xuICAgICAgICAgICAgICB0eXBlOiBTY3JhdGNoLkFyZ3VtZW50VHlwZS5TVFJJTkcsXG4gICAgICAgICAgICAgIGRlZmF1bHRWYWx1ZTogJ0hFTExPIFdPUkxEJ1xuICAgICAgICAgICAgfVxuICAgICAgICAgIH1cbiAgICAgICAgfSxcbiAgICAgICAge1xuICAgICAgICAgIG9wY29kZTogJ2lzTGVzc09yRXF1YWwnLFxuXG4gICAgICAgICAgYmxvY2tUeXBlOiBTY3JhdGNoLkJsb2NrVHlwZS5CT09MRUFOLFxuXG4gICAgICAgICAgdGV4dDogJ1tBXSA8PSBbQl0nLFxuICAgICAgICAgIGFyZ3VtZW50czoge1xuICAgICAgICAgICAgQToge1xuICAgICAgICAgICAgICB0eXBlOiBTY3JhdGNoLkFyZ3VtZW50VHlwZS5OVU1CRVJcbiAgICAgICAgICAgIH0sXG4gICAgICAgICAgICBCOiB7XG4gICAgICAgICAgICAgIHR5cGU6IFNjcmF0Y2guQXJndW1lbnRUeXBlLk5VTUJFUixcbiAgICAgICAgICAgICAgZGVmYXVsdFZhbHVlOiA1MFxuICAgICAgICAgICAgfVxuICAgICAgICAgIH1cbiAgICAgICAgfSxcbiAgICAgICAge1xuICAgICAgICAgIG9wY29kZTogJ2lzTW9yZU9yRXF1YWwnLFxuXG4gICAgICAgICAgYmxvY2tUeXBlOiBTY3JhdGNoLkJsb2NrVHlwZS5CT09MRUFOLFxuXG4gICAgICAgICAgdGV4dDogJ1tBXT49IFtCXScsXG4gICAgICAgICAgYXJndW1lbnRzOiB7XG4gICAgICAgICAgICBBOiB7XG4gICAgICAgICAgICAgIHR5cGU6IFNjcmF0Y2guQXJndW1lbnRUeXBlLk5VTUJFUlxuICAgICAgICAgICAgfSxcbiAgICAgICAgICAgIEI6IHtcbiAgICAgICAgICAgICAgdHlwZTogU2NyYXRjaC5Bcmd1bWVudFR5cGUuTlVNQkVSLFxuICAgICAgICAgICAgICBkZWZhdWx0VmFsdWU6IDUwXG4gICAgICAgICAgICB9XG4gICAgICAgICAgfVxuICAgICAgICB9LFxuICAgICAgICB7XG4gICAgICAgICAgb3Bjb2RlOiAndHJ1ZUJsb2NrJyxcbiAgICAgICAgICBibG9ja1R5cGU6IFNjcmF0Y2guQmxvY2tUeXBlLkJPT0xFQU4sXG4gICAgICAgICAgdGV4dDogJ3RydWUnXG4gICAgICAgIH0sXG4gICAgICAgIHtcbiAgICAgICAgICBvcGNvZGU6ICdmYWxzZUJsb2NrJyxcbiAgICAgICAgICBibG9ja1R5cGU6IFNjcmF0Y2guQmxvY2tUeXBlLkJPT0xFQU4sXG4gICAgICAgICAgdGV4dDogJ2ZhbHNlJ1xuICAgICAgICB9LFxuICAgICAgICB7XG4gICAgICAgICAgb3Bjb2RlOiAnZXhwb25lbnQnLFxuXG4gICAgICAgICAgYmxvY2tUeXBlOiBTY3JhdGNoLkJsb2NrVHlwZS5SRVBPUlRFUixcblxuICAgICAgICAgIHRleHQ6ICdbQV0gXiBbQl0nLFxuICAgICAgICAgIGFyZ3VtZW50czoge1xuICAgICAgICAgICAgQToge1xuICAgICAgICAgICAgICB0eXBlOiBTY3JhdGNoLkFyZ3VtZW50VHlwZS5OVU1CRVJcbiAgICAgICAgICAgIH0sXG4gICAgICAgICAgICBCOiB7XG4gICAgICAgICAgICAgIHR5cGU6IFNjcmF0Y2guQXJndW1lbnRUeXBlLk5VTUJFUlxuICAgICAgICAgICAgfVxuICAgICAgICAgIH1cbiAgICAgICAgfSxcbiAgICAgICAge1xuICAgICAgICAgIG9wY29kZTogJ3BpJyxcbiAgICAgICAgICBibG9ja1R5cGU6IFNjcmF0Y2guQmxvY2tUeXBlLlJFUE9SVEVSLFxuICAgICAgICAgIHRleHQ6ICdwaSdcbiAgICAgICAgfSxcbiAgICAgICAge1xuICAgICAgICAgIG9wY29kZTogJ3Rlcm5hcnlPcGVyYXRvcicsXG5cbiAgICAgICAgICBibG9ja1R5cGU6IFNjcmF0Y2guQmxvY2tUeXBlLlJFUE9SVEVSLFxuXG4gICAgICAgICAgdGV4dDogJ2lmIFtBXSB0aGVuIFtCXSBlbHNlIFtDXScsXG4gICAgICAgICAgYXJndW1lbnRzOiB7XG4gICAgICAgICAgICBBOiB7XG4gICAgICAgICAgICAgIHR5cGU6IFNjcmF0Y2guQXJndW1lbnRUeXBlLkJPT0xFQU5cbiAgICAgICAgICAgIH0sXG4gICAgICAgICAgICBCOiB7XG4gICAgICAgICAgICAgIHR5cGU6IFNjcmF0Y2guQXJndW1lbnRUeXBlLlNUUklORyxcbiAgICAgICAgICAgICAgZGVmYXVsdFZhbHVlOiAnYmFuYW5hJ1xuICAgICAgICAgICAgfSxcbiAgICAgICAgICAgIEM6IHtcbiAgICAgICAgICAgICAgdHlwZTogU2NyYXRjaC5Bcmd1bWVudFR5cGUuU1RSSU5HLFxuICAgICAgICAgICAgICBkZWZhdWx0VmFsdWU6ICdhcHBsZSdcbiAgICAgICAgICAgIH1cbiAgICAgICAgICB9XG4gICAgICAgIH0sXG4gICAgICAgIHtcbiAgICAgICAgICBvcGNvZGU6ICdsZXR0ZXJzJyxcblxuICAgICAgICAgIGJsb2NrVHlwZTogU2NyYXRjaC5CbG9ja1R5cGUuUkVQT1JURVIsXG5cbiAgICAgICAgICB0ZXh0OiAnbGV0dGVycyBbU1RBUlRdIHRvIFtFTkRdIG9mIFtTVFJJTkddJyxcbiAgICAgICAgICBhcmd1bWVudHM6IHtcbiAgICAgICAgICAgIFNUQVJUOiB7XG4gICAgICAgICAgICAgIHR5cGU6IFNjcmF0Y2guQXJndW1lbnRUeXBlLk5VTUJFUixcbiAgICAgICAgICAgICAgZGVmYXVsdFZhbHVlOiA1XG4gICAgICAgICAgICB9LFxuICAgICAgICAgICAgRU5EOiB7XG4gICAgICAgICAgICAgIHR5cGU6IFNjcmF0Y2guQXJndW1lbnRUeXBlLk5VTUJFUixcbiAgICAgICAgICAgICAgZGVmYXVsdFZhbHVlOiA3XG4gICAgICAgICAgICB9LFxuICAgICAgICAgICAgU1RSSU5HOiB7XG4gICAgICAgICAgICAgIHR5cGU6IFNjcmF0Y2guQXJndW1lbnRUeXBlLlNUUklORyxcbiAgICAgICAgICAgICAgZGVmYXVsdFZhbHVlOiAnVGhpcyBpcyBhIHN0cmluZy4nXG4gICAgICAgICAgICB9XG4gICAgICAgICAgfVxuICAgICAgICB9LFxuICAgICAgICB7XG4gICAgICAgICAgb3Bjb2RlOiAnY3VycmVudE1pbGxpc2Vjb25kJyxcbiAgICAgICAgICBibG9ja1R5cGU6IFNjcmF0Y2guQmxvY2tUeXBlLlJFUE9SVEVSLFxuICAgICAgICAgIHRleHQ6ICdjdXJyZW50IG1pbGxpc2Vjb25kJ1xuICAgICAgICB9LFxuICAgICAgICB7XG4gICAgICAgICAgb3Bjb2RlOiAnZmV0Y2hGcm9tJyxcblxuICAgICAgICAgIGJsb2NrVHlwZTogU2NyYXRjaC5CbG9ja1R5cGUuUkVQT1JURVIsXG5cbiAgICAgICAgICB0ZXh0OiAncGxheSBmZXRjaCB3aXRoIFVSTCBbVVJMXScsXG4gICAgICAgICAgYXJndW1lbnRzOiB7XG4gICAgICAgICAgICBVUkw6IHtcbiAgICAgICAgICAgICAgdHlwZTogU2NyYXRjaC5Bcmd1bWVudFR5cGUuU1RSSU5HLFxuICAgICAgICAgICAgICBkZWZhdWx0VmFsdWU6ICdodHRwczovL3RyYW5zbGF0ZS1zZXJ2aWNlLnNjcmF0Y2gubWl0LmVkdS90cmFuc2xhdGU/bGFuZ3VhZ2U9ZW8mdGV4dD1oZWxsbydcbiAgICAgICAgICAgIH1cbiAgICAgICAgICB9XG4gICAgICAgIH0sXG4gICAgICAgIHtcbiAgICAgICAgICBvcGNvZGU6ICdwYXJzZUpTT04nLFxuXG4gICAgICAgICAgYmxvY2tUeXBlOiBTY3JhdGNoLkJsb2NrVHlwZS5SRVBPUlRFUixcblxuICAgICAgICAgIHRleHQ6ICdbUEFUSF0gb2YgW0pTT05fU1RSSU5HXScsXG4gICAgICAgICAgYXJndW1lbnRzOiB7XG4gICAgICAgICAgICBQQVRIOiB7XG4gICAgICAgICAgICAgIHR5cGU6IFNjcmF0Y2guQXJndW1lbnRUeXBlLlNUUklORyxcbiAgICAgICAgICAgICAgZGVmYXVsdFZhbHVlOiAnZnJ1aXQgLyBhcHBsZXMnXG4gICAgICAgICAgICB9LFxuICAgICAgICAgICAgSlNPTl9TVFJJTkc6IHtcbiAgICAgICAgICAgICAgdHlwZTogU2NyYXRjaC5Bcmd1bWVudFR5cGUuU1RSSU5HLFxuICAgICAgICAgICAgICBkZWZhdWx0VmFsdWU6ICd7XCJmcnVpdFwiOiB7XCJhcHBsZXNcIjogMiwgXCJiYW5hbmFzXCI6IDN9LCBcInRvdGFsX2ZydWl0XCI6IDV9J1xuICAgICAgICAgICAgfVxuICAgICAgICAgIH1cbiAgICAgICAgfSxcbiAgICAgICAge1xuICAgICAgICAgIG9wY29kZTogJ3N0cmluZ1RvQm9vbGVhbicsXG5cbiAgICAgICAgICBibG9ja1R5cGU6IFNjcmF0Y2guQmxvY2tUeXBlLkJPT0xFQU4sXG5cbiAgICAgICAgICB0ZXh0OiAnW1NUUklOR10nLFxuICAgICAgICAgIGFyZ3VtZW50czoge1xuICAgICAgICAgICAgU1RSSU5HOiB7XG4gICAgICAgICAgICAgIHR5cGU6IFNjcmF0Y2guQXJndW1lbnRUeXBlLlNUUklORyxcbiAgICAgICAgICAgICAgZGVmYXVsdFZhbHVlOiAndHJ1ZSdcbiAgICAgICAgICAgIH1cbiAgICAgICAgICB9XG4gICAgICAgIH0sXG4gICAgICAgIHtcbiAgICAgICAgICBvcGNvZGU6ICdyZWdleFJlcGxhY2UnLFxuXG4gICAgICAgICAgYmxvY2tUeXBlOiBTY3JhdGNoLkJsb2NrVHlwZS5SRVBPUlRFUixcblxuICAgICAgICAgIHRleHQ6ICdyZXBsYWNlIFtTVFJJTkddIHVzaW5nIHRoZSBydWxlIFtSRUdFWF0gd2l0aCBbTkVXU1RSSU5HXScsXG4gICAgICAgICAgYXJndW1lbnRzOiB7XG4gICAgICAgICAgICBTVFJJTkc6IHtcbiAgICAgICAgICAgICAgdHlwZTogU2NyYXRjaC5Bcmd1bWVudFR5cGUuU1RSSU5HLFxuICAgICAgICAgICAgICBkZWZhdWx0VmFsdWU6ICdiYW5hbmFzIGFyZSBhd2Vzb21lLiBpIGxpa2UgYmFuYW5hcy4gJ1xuICAgICAgICAgICAgfSxcbiAgICAgICAgICAgIFJFR0VYOiB7XG4gICAgICAgICAgICAgIHR5cGU6IFNjcmF0Y2guQXJndW1lbnRUeXBlLlNUUklORyxcbiAgICAgICAgICAgICAgZGVmYXVsdFZhbHVlOiAnYmFuYW5hJ1xuICAgICAgICAgICAgfSxcbiAgICAgICAgICAgIE5FV1NUUklORzoge1xuICAgICAgICAgICAgICB0eXBlOiBTY3JhdGNoLkFyZ3VtZW50VHlwZS5TVFJJTkcsXG4gICAgICAgICAgICAgIGRlZmF1bHRWYWx1ZTogJ2FwcGxlJ1xuICAgICAgICAgICAgfVxuICAgICAgICAgIH1cbiAgICAgICAgfVxuICAgICAgXVxuICAgIH1cbiAgfVxuXG4gIGlzRXhhY3RseSAoe0EsIEJ9KSB7XG4gICAgcmV0dXJuIEEgPT09IEI7XG4gIH1cblxuICBpc0xlc3NPckVxdWFsICh7QSwgQn0pIHtcbiAgICByZXR1cm4gQSA8PSBCO1xuICB9XG5cbiAgaXNNb3JlT3JFcXVhbCAoe0EsIEJ9KSB7XG4gICAgcmV0dXJuIEE+PSBCO1xuICB9XG5cbiAgdHJ1ZUJsb2NrICgpIHtcbiAgICByZXR1cm4gdHJ1ZTtcbiAgfVxuXG4gIGZhbHNlQmxvY2sgKCkge1xuICAgIHJldHVybiBmYWxzZTtcbiAgfVxuXG4gIGV4cG9uZW50ICh7QSwgQn0pIHtcbiAgICByZXR1cm4gTWF0aC5wb3cgKEEsIEIpO1xuICB9XG5cbiAgcGkgKCkge1xuICAgIHJldHVybiBNYXRoLlBJO1xuICB9XG5cbiAgdGVybmFyeU9wZXJhdG9yICh7QSwgQiwgQ30pIHtcbiAgICByZXR1cm4gQT8gQjogQztcbiAgfVxuXG4gIGxldHRlcnMgKHtTVFJJTkcsIFNUQVJULCBFTkR9KSB7XG4gICAgcmV0dXJuIFNUUklORy5zbGljZSAoTWF0aC5tYXggKDEsIFNUQVJUKSAtIDEsIE1hdGgubWluIChTVFJJTkcubGVuZ3RoLCBFTkQpKTtcbiAgfVxuXG4gIGN1cnJlbnRNaWxsaXNlY29uZCAoKSB7XG4gICAgcmV0dXJuIERhdGUubm93ICgpJSAxMDAwO1xuICB9XG5cbiAgZmV0Y2hGcm9tICh7VVJMfSkge1xuICAgIHJldHVybiBmZXRjaCAoVVJMKSAudGhlbiAocmVzID0+IHJlcy50ZXh0ICgpKVxuICAgICAgLmNhdGNoIChlcnIgPT4gJycpO1xuICB9XG5cbiAgcGFyc2VKU09OICh7UEFUSCwgSlNPTl9TVFJJTkd9KSB7XG4gICAgdHJ5IHtcbiAgICAgIGNvbnN0IHBhdGggPSBQQVRILnRvU3RyaW5nICgpLiBzcGxpdCAoJy8nKS4gbWFwIChwcm9wID0+IGRlY29kZVVSSUNvbXBvbmVudCAocHJvcCkpO1xuICAgICAgaWYgKHBhdGggWzBdID09PSAnJykgcGF0aC5zcGxpY2UgKDAsIDEpO1xuICAgICAgaWYgKHBhdGggW3BhdGgubGVuZ3RoIC0gMV0gPT09ICcnKSBwYXRoLnNwbGljZSAoLTEsIDEpO1xuICAgICAgbGV0IGpzb247XG4gICAgICB0cnkge1xuICAgICAgICBqc29uID0gSlNPTi5wYXJzZSAoJycgKyBKU09OX1NUUklORyk7XG4gICAgICB9IGNhdGNoIChlKSB7XG4gICAgICAgIHJldHVybiBlLm1lc3NhZ2U7XG4gICAgICB9XG4gICAgICBwYXRoLmZvckVhY2ggKHByb3AgPT4ganNvbiA9IGpzb24gW3Byb3BdKTtcbiAgICAgIGlmIChqc29uID09PSBudWxsKSByZXR1cm4gJ251bGwnO1xuICAgICAgZWxzZSBpZiAoanNvbiA9PT0gdW5kZWZpbmVkKSByZXR1cm4gJyc7XG4gICAgICBlbHNlIGlmICh0eXBlb2YganNvbiA9PT0gJ29iamVjdCcpIHJldHVybiBKU09OLnN0cmluZ2lmeSAoanNvbik7XG4gICAgICBlbHNlIHJldHVybiBqc29uLnRvU3RyaW5nICgpO1xuICAgIH0gY2F0Y2ggKGVycikge1xuICAgICAgcmV0dXJuICcnO1xuICAgIH1cbiAgfVxuXG4gIHN0cmluZ1RvQm9vbGVhbiAoe1NUUklOR30pIHtcbiAgICByZXR1cm4gU1RSSU5HO1xuICB9XG5cbiAgcmVnZXhSZXBsYWNlICh7U1RSSU5HLCBSRUdFWCwgTkVXU1RSSU5HfSkge1xuICAgIHJldHVybiBTVFJJTkcudG9TdHJpbmcgKCkuIHJlcGxhY2UgKG5ldyBSZWdFeHAgKFJFR0VYLCAnZ2knKSwgTkVXU1RSSU5HKTtcbiAgfVxuXG59XG5cblNjcmF0Y2guZXh0ZW5zaW9ucy5yZWdpc3RlciAobmV3IEltcHJvdmVkVXRpbCAoKSk7Iiwib3B0aW9ucyI6eyJwYXJzZXJPcHRpb25zIjp7ImVjbWFWZXJzaW9uIjoxMiwic291cmNlVHlwZSI6InNjcmlwdCIsImVjbWFGZWF0dXJlcyI6e319LCJydWxlcyI6eyJjb25zdHJ1Y3Rvci1zdXBlciI6MiwiZm9yLWRpcmVjdGlvbiI6MiwiZ2V0dGVyLXJldHVybiI6Miwibm8tYXN5bmMtcHJvbWlzZS1leGVjdXRvciI6Miwibm8tY2FzZS1kZWNsYXJhdGlvbnMiOjIsIm5vLWNsYXNzLWFzc2lnbiI6Miwibm8tY29tcGFyZS1uZWctemVybyI6Miwibm8tY29uZC1hc3NpZ24iOjIsIm5vLWNvbnN0LWFzc2lnbiI6Miwibm8tY29uc3RhbnQtY29uZGl0aW9uIjoyLCJuby1jb250cm9sLXJlZ2V4IjoyLCJuby1kZWJ1Z2dlciI6Miwibm8tZGVsZXRlLXZhciI6Miwibm8tZHVwZS1hcmdzIjoyLCJuby1kdXBlLWNsYXNzLW1lbWJlcnMiOjIsIm5vLWR1cGUtZWxzZS1pZiI6Miwibm8tZHVwZS1rZXlzIjoyLCJuby1kdXBsaWNhdGUtY2FzZSI6Miwibm8tZW1wdHkiOjIsIm5vLWVtcHR5LWNoYXJhY3Rlci1jbGFzcyI6Miwibm8tZW1wdHktcGF0dGVybiI6Miwibm8tZXgtYXNzaWduIjoyLCJuby1leHRyYS1ib29sZWFuLWNhc3QiOjIsIm5vLWV4dHJhLXNlbWkiOjIsIm5vLWZhbGx0aHJvdWdoIjoyLCJuby1mdW5jLWFzc2lnbiI6Miwibm8tZ2xvYmFsLWFzc2lnbiI6Miwibm8taW1wb3J0LWFzc2lnbiI6Miwibm8taW5uZXItZGVjbGFyYXRpb25zIjoyLCJuby1pbnZhbGlkLXJlZ2V4cCI6Miwibm8taXJyZWd1bGFyLXdoaXRlc3BhY2UiOjIsIm5vLW1pc2xlYWRpbmctY2hhcmFjdGVyLWNsYXNzIjoyLCJuby1taXhlZC1zcGFjZXMtYW5kLXRhYnMiOjIsIm5vLW5ldy1zeW1ib2wiOjIsIm5vLW9iai1jYWxscyI6Miwibm8tb2N0YWwiOjIsIm5vLXByb3RvdHlwZS1idWlsdGlucyI6Miwibm8tcmVkZWNsYXJlIjoyLCJuby1yZWdleC1zcGFjZXMiOjIsIm5vLXNlbGYtYXNzaWduIjoyLCJuby1zZXR0ZXItcmV0dXJuIjoyLCJuby1zaGFkb3ctcmVzdHJpY3RlZC1uYW1lcyI6Miwibm8tc3BhcnNlLWFycmF5cyI6Miwibm8tdGhpcy1iZWZvcmUtc3VwZXIiOjIsIm5vLXVuZGVmIjoyLCJuby11bmV4cGVjdGVkLW11bHRpbGluZSI6Miwibm8tdW5yZWFjaGFibGUiOjIsIm5vLXVuc2FmZS1maW5hbGx5IjoyLCJuby11bnNhZmUtbmVnYXRpb24iOjIsIm5vLXVudXNlZC1sYWJlbHMiOjIsIm5vLXVudXNlZC12YXJzIjoyLCJuby11c2VsZXNzLWNhdGNoIjoyLCJuby11c2VsZXNzLWVzY2FwZSI6Miwibm8td2l0aCI6MiwicmVxdWlyZS15aWVsZCI6MiwidXNlLWlzbmFuIjoyLCJ2YWxpZC10eXBlb2YiOjJ9LCJlbnYiOnt9fX0=) to catch these kinds of errors.

![image](https://user-images.githubusercontent.com/22133785/123342095-fbbcba80-d503-11eb-8803-ec9194dc96f4.png)

You just need to add `/* global fetch, Scratch */` at the beginning to suppress the errors about `Scratch` and `fetch` being undefined
