### ISSUE TITLE
See changes for `16-9` in:

### ISSUE THREAD

**Issue by TheMapotakes** [SheepTester/scratch-gui#57]
See changes for `16-9` in:
- [`scratch-gui`](https://github.com/SheepTester/scratch-gui/commits/16-9?author=SheepTester)
- [`scratch-vm`](https://github.com/SheepTester/scratch-vm/commits/16-9?author=SheepTester)
- [`scratch-paint`](https://github.com/SheepTester/scratch-paint/commits/16-9?author=SheepTester)

_Originally posted by @SheepTester in https://github.com/SheepTester/scratch-gui/issues/7#issuecomment-568580115_

**Comment by SheepTester** [comment]
What is this for?

**Comment by TheMapotakes** [comment]
Extension

**Comment by TheMapotakes** [comment]
d

**Comment by TheMapotakes** [comment]
sess

**Comment by TheMapotakes** [comment]
Bumboopblee

**Comment by SheepTester** [comment]
> Extension

Say more.

**Comment by TheMapotakes** [comment]
Extension

**Comment by SheepTester** [comment]
> Extension

What kind? A time extension? A browser extension? An extension cord? A Scratch extension?

For what? Because you were bored? To add a new capability to your project?

I do not understand what this issue is for. If I continue to not understand it after a while, I will close this for spam.

**Comment by TheMapotakes** [comment]
Link URL please.

**Comment by SheepTester** [comment]
Do you want the ability to link a URL? If so, how so? If not, do you want me to give you a URL? If so, to where?

**Comment by TheMapotakes** [comment]
From Extension

**Comment by SheepTester** [comment]
Ah, got it. Thanks for the clarification!

To load an unofficial extension from a URL, head to the extensions library (click on the blue button in the bottom left corner) and click on "Choose an extension: For developers." In the prompt that appears, you can enter the URL to your unofficial extension, and it'll be added.

Closing this issue as this feature already exists. Have a nice day!
