### ISSUE TITLE
Can't see Y position of sprites when using vertical dimensions

### ISSUE THREAD

**Issue by AngelFireLA** [SheepTester/scratch-gui#58]
### Expected Behavior

We should see the full x and y coords

### Actual Behavior

I can see the x position but the y position is hidden behind the stage presentation

### Steps to Reproduce

puth the width to 375  and height to 580 and then you can not see the y position anymore

### Operating System and Browser

Windows 10 and googe chrome

**Comment by SheepTester** [comment]
You can still see the y position when using the small stage view
![image](https://user-images.githubusercontent.com/22133785/128548851-b37a9393-aa62-46af-a759-ebcf609c5c55.png)
