### ISSUE TITLE
README describes install instructions for LLK's Scratch GUI

### ISSUE THREAD

**Issue by TeleKiwi** [SheepTester/scratch-gui#66]
### Expected Behavior

The command in the README to install this via NPM should reference this repo. e.g `npm install https://github.com/SheepTester/scratch-gui.git`

### Actual Behavior

It actually references the repo that this was forked from. e.g `npm install https://github.com/LLK/scratch-gui.git`

### Steps to Reproduce

1. Go to the README and scroll down to the install instructions. Notice what repo the link references.

### Operating System and Browser

Windows 10
Opera GX

**Comment by UtterDonkey** [comment]
I have fixed the issue and created a pull request. Hopefully SheepTester merges it.

**Comment by TeleKiwi** [comment]
Closing this now 'cause UtterDonkey's PR got merged.
