### ISSUE TITLE
How to change theme colour? (forked)

### ISSUE THREAD

**Issue by theycallhermax** [SheepTester/scratch-gui#69]
Hi, I recently forked E羊iquices, and I noticed that there is a diffrent colour scheme. Can I change it, and make it have effect on the `gh-pages` branch, cause ST answered my question, but it was on the `develop` branch. I pointed that out to them, then all of the sudden, weeks later, nobody answers ever again.

**Comment by SheepTester** [comment]
See 574b7d50cc6bb961b51f6e8f2748d704b363075c for the commit where I changed the menu bar colour

To deploy your mod to GitHub Pages, follow https://github.com/LLK/scratch-gui/wiki/Publishing-to-GitHub-Pages

**Comment by theycallhermax** [comment]
I don't understand.

**Comment by SheepTester** [comment]
Which part?

**Comment by theycallhermax** [comment]
I don't understand how to make the changes have effect on the `gh-pages` branch.

**Comment by SheepTester** [comment]
Follow the instructions at https://github.com/LLK/scratch-gui/wiki/Publishing-to-GitHub-Pages

**Comment by theycallhermax** [comment]
I already published my mod to GitHub Pages

**Comment by SheepTester** [comment]
You need to do it again every time you make changes to your mod.
