### ISSUE TITLE
How do you import extension from URL?

### ISSUE THREAD

**Issue by CommanderGL** [SheepTester/scratch-gui#73]
Hi, I'm making my own scratch-gui and I was wondering how you added import extension by URL. Thank You.

**Comment by SheepTester** [comment]
Here were the changes I made to the [scratch-gui](https://github.com/SheepTester/scratch-gui/commit/b4024c6e6c2fc8202d6301920b9a2fce54ff079e) and [scratch-vm](https://github.com/SheepTester/scratch-vm/commit/06765ebebdcf9eba6ab1ededf9b2c91a55bcc016), respectively.

**Comment by CommanderGL** [comment]
I was wondering how you did the plugins.

**Comment by SheepTester** [comment]
https://github.com/SheepTester/scratch-gui/commit/fbc9982c54fade3c3e08a3aa25591bf402e9a929#diff-a97e7eff42bf42b3d37d89dc4442547077f542752c92580821f5be85f6d0eeb5R76-R81

**Comment by CommanderGL** [comment]
Thank You! I added both.
